### ISSUE TITLE
Add Exported Spellbook to Inventory

### ISSUE THREAD

**Issue by RinVindor** [HadaIonut/spellbook-master#3]
I'm not sure if this is possible (if so its not working on my current game), but it'd be great to be able to export the spellbook and then drag that into the player's inventory.

**Comment by flamewave000** [comment]
I would like to expand on this ticket. The issue is not that the module prevents it, but rather something is corrupt with the spellbook item that has been generated. It cannot be drag and dropped into an inventory. I get the following crash report in the console. It appears that something is going wrong when it is attempting to update the data in the actor using the data in the item.

![image](https://user-images.githubusercontent.com/3588046/121543131-aeeec500-c9d6-11eb-982e-765cbe597205.png)
![image](https://user-images.githubusercontent.com/3588046/121543262-c4fc8580-c9d6-11eb-8762-4ea0ea261f43.png)

**Comment by flamewave000** [comment]
I've opened PR #4 that fixes this issue.

**Comment by HadaIonut** [comment]
Thx for the PR I will be packaging a release for this in a bit
